name: Auto Restart Codespaces

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  restart_codespaces:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Restart All Codespaces
        env:
          TOKEN_1: ${{ secrets.TOKEN_1 }}
          TOKEN_2: ${{ secrets.TOKEN_2 }}
          TOKEN_3: ${{ secrets.TOKEN_3 }}
          TOKEN_4: ${{ secrets.TOKEN_4 }}
          TOKEN_5: ${{ secrets.TOKEN_5 }}
          TOKEN_6: ${{ secrets.TOKEN_6 }}
          TOKEN_7: ${{ secrets.TOKEN_7 }}
          TOKEN_8: ${{ secrets.TOKEN_8 }}
          TOKEN_9: ${{ secrets.TOKEN_9 }}
          TOKEN_10: ${{ secrets.TOKEN_10 }}
        run: |
          declare -A token_map=(
            ["TOKEN_1"]="redesigned-invention-v6q7xx5v4rwv2www5 miniature-dollop-wrgjww476j7xh5wwr"
            ["TOKEN_2"]="codespace-legendary-acorn-q7p5949rg55xc4grv codespace-miniature-eureka-wrgq9596jjjgh9xwx"
            ["TOKEN_3"]="codespace-5 codespace-6"
            ["TOKEN_4"]="codespace-7 codespace-8"
            ["TOKEN_5"]="codespace-9 codespace-10"
            ["TOKEN_6"]="codespace-11 codespace-12"
            ["TOKEN_7"]="codespace-13 codespace-14"
            ["TOKEN_8"]="codespace-15 codespace-16"
            ["TOKEN_9"]="codespace-17 codespace-18"
            ["TOKEN_10"]="codespace-19 codespace-20"
          )

          for token_key in "${!token_map[@]}"; do
            export GH_TOKEN="${!token_key}"

            for codespace in ${token_map[$token_key]}; do
              echo "Checking $codespace..."
              STATUS=$(gh codespace list --json name,state | jq -r --arg name "$codespace" '.[] | select(.name == $name) | .state')

              echo "Status of $codespace: $STATUS"

              if [ "$STATUS" = "Shutdown" ]; then
                echo "Starting $codespace..."
                gh codespace ssh -c "$codespace" -- true
              else
                echo "$codespace is already running."
              fi
            done
          done
